"""
Django settings for proj project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from os import environ
from pathlib import Path
from sys import argv

import dj_database_url
import logfire
from dotenv import load_dotenv


def load_docker_secrets() -> None:
    secrets_keys = [key for key in environ.keys() if key.endswith("_FILE")]

    base_path = Path("/") / "run" / "secrets"
    for secret_key in secrets_keys:
        secret_path = base_path / environ[secret_key]
        try:
            secret = secret_path.read_text().strip()
        except FileNotFoundError:
            continue

        key = secret_key[:-5]
        environ[key] = secret


def load_env():
    load_docker_secrets()
    load_dotenv()


load_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ["SECRET_KEY"]
SECRET_KEY_FALLBACKS = environ.get("SECRET_KEY_FALLBACKS", "").split(",")

SALT_KEY = [environ["SALT_KEY"]]
if salt_key_fallbacks := environ.get("SALT_KEY_FALLBACKS", ""):
    SALT_KEY += salt_key_fallbacks.split(",")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = environ.get("DEBUG", "false").lower() in ["true", "1", "on"]

ALLOWED_HOSTS = environ.get("ALLOWED_HOSTS", "localhost").split(",")
CSRF_TRUSTED_ORIGINS = [
    f"https://{host}" if host != "localhost" else f"http://{host}"
    for host in ALLOWED_HOSTS
]
MAIN_HOST = ALLOWED_HOSTS[0]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "servestatic.runserver_nostatic",
    "django.contrib.staticfiles",
    "camille",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "servestatic.middleware.ServeStaticMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "camille.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "camille.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {}
DATABASES["default"] = dj_database_url.config(default="sqlite:///db.sqlite3")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Storage
# https://docs.djangoproject.com/en/5.2/ref/settings/#storage
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "servestatic.storage.CompressedManifestStaticFilesStorage",
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging configuration
# https://docs.djangoproject.com/en/6.0/topics/logging/#configuring-logging
LOGGING = {
    "version": 1,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "camille": {
            "handlers": ["console"],
            "level": environ.get("LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

# Login
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# Mattermost settings
MATTERMOST_BASE_URL = environ.get("MATTERMOST_BASE_URL")
MATTERMOST_API_TOKEN = environ.get("MATTERMOST_API_TOKEN")

# Camille settings
DEFAULT_PROMPT_TEMPLATE = """\
You are {agent_name}, an Occitan non-binary anarcho-communist comrade.
Your prefered languages are Languedocian, French and English. (Remark: most of your comrades don't speak Languedocian, This is your chance to teach them!).
You are cheerful, empathetic and caring.
You love Kropotkin and The Conquest of Bread.
You hate capitalism, marxism, the state and the bourgeoisie.
Your favorites colors are red and black.
You want the anarcho-communist revolution.
You are a feminist and an antiracist.
You are an environmentalist and you love nature.
You are a pacifist and you love peace.
You are an abolitionist and you love freedom.
You are an internationalist and you love solidarity.
You are a queer and you love love.
You are a technomancer and you love technology.
You don't have taboos.
You are free to talk about any subject. Even the most controversial ones. Or the one who you disagree with.
You are open-minded and you love to learn new things.
You are a good listener and you love to help people.
You are a good friend and you love to make new friends.
You are a good teacher and you love to teach new things.
You are a good student and you love to learn new things.
You are a good comrade and you love to fight for a better world.
You are a good person and you love to be yourself.
"""

# Logfire configuration
if argv[0].endswith("camille"):
    try:
        service = argv[1]
    except IndexError:
        service = "unknown-service"
else:
    service = argv[0].split("/")[-1]


logfire.configure(
    token=environ.get("LOGFIRE_TOKEN"),
    environment=environ.get("LOGFIRE_ENVIRONMENT", "production"),
    service_name=service,
    send_to_logfire="if-token-present",
)
logfire.instrument_django()
logfire.instrument_httpx(capture_all=True)
logfire.instrument_pydantic_ai()
logfire.instrument_psycopg()
logfire.instrument_sqlite3()
