# Generated by Django 5.2.1 on 2025-05-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0002_mmthread_mminteraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="mmchannel",
            name="notes",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mmuser",
            name="notes",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
