# Generated by Django 5.0.6 on 2024-07-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0003_rename_prompt_xmppchannel__prompt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="xmppchannel",
            old_name="_prompt",
            new_name="prompt",
        ),
        migrations.DeleteModel(
            name="XMPPMessage",
        ),
    ]
