# Generated by Django 5.0.6 on 2024-07-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0005_alter_xmppchannel_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="xmppchannel",
            name="llm_model",
            field=models.CharField(
                choices=[
                    ("gemini-1.5-flash-latest", "Gemini Flash"),
                    ("gemini-1.5-pro-latest", "Gemini Pro"),
                ],
                default="gemini-1.5-flash-latest",
                max_length=64,
            ),
        ),
    ]
