# Generated by Django 5.2.1 on 2025-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0005_remove_mminteraction_tokens_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mmchannel",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="mmchannel",
            name="header",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mmchannel",
            name="purpose",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mmteam",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="mmuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="mmuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="mmuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
