# Generated by Django 5.1.1 on 2024-09-05 21:46

import django.db.models.deletion
from django.db import migrations, models


def migrate_channels(apps, schema_editor):

    db_alias = schema_editor.connection.alias
    XMPPChannel = apps.get_model("camille", "XMPPChannel")
    LLMConversation = apps.get_model("camille", "LLMConversation")

    for channel in XMPPChannel.objects.using(db_alias).filter(conversation=None):
        channel.conversation = LLMConversation.objects.using(db_alias).create(
            llm_model=channel.llm_model,
            prompt=channel.prompt,
        )
        channel.save()


def reverse_migrate_channels(apps, schema_editor):

    db_alias = schema_editor.connection.alias
    XMPPChannel = apps.get_model("camille", "XMPPChannel")

    for channel in XMPPChannel.objects.using(db_alias).all():
        channel.llm_model = channel.conversation.llm_model
        channel.prompt = channel.conversation.prompt
        channel.save()


class Migration(migrations.Migration):

    replaces = [
        ("camille", "0009_llmconversation_xmppchannel_conversation"),
        ("camille", "0010_auto_20240905_2336"),
        ("camille", "0011_remove_xmppchannel_llm_model_and_more"),
    ]

    dependencies = [
        ("camille", "0008_alter_xmppchannel_llm_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        choices=[
                            ("gemini-1.5-flash-latest", "Gemini Flash"),
                            ("gemini-1.5-pro-latest", "Gemini Pro"),
                        ],
                        default="gemini-1.5-flash-latest",
                        max_length=64,
                    ),
                ),
                ("prompt", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.AddField(
            model_name="xmppchannel",
            name="conversation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="camille.llmconversation",
            ),
        ),
        migrations.RunPython(
            code=migrate_channels,
            reverse_code=reverse_migrate_channels,
            atomic=True,
        ),
        migrations.RemoveField(
            model_name="xmppchannel",
            name="llm_model",
        ),
        migrations.RemoveField(
            model_name="xmppchannel",
            name="prompt",
        ),
        migrations.AlterField(
            model_name="xmppchannel",
            name="conversation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="camille.llmconversation",
            ),
        ),
    ]
