# Generated by Django 5.1.1 on 2024-09-10 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0012_llmmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="MMUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mmid", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_agent", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MMChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mmid", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mm_channel",
                        related_query_name="mm_channel",
                        to="camille.llmconversation",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="channels", to="camille.mmuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SHSession",
            fields=[
                (
                    "username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shell_session",
                        related_query_name="shell_session",
                        to="camille.llmconversation",
                    ),
                ),
            ],
        ),
    ]
