# Generated by Django 5.1.1 on 2024-09-10 19:46

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0014_alter_mmchannel_conversation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mmchannel",
            name="users",
        ),
        migrations.RemoveField(
            model_name="mmchannel",
            name="name",
        ),
        migrations.AlterField(
            model_name="mmchannel",
            name="conversation",
            field=models.OneToOneField(
                default=django.db.models.query.QuerySet.create,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mm_channel",
                related_query_name="mm_channel",
                to="camille.llmconversation",
            ),
        ),
        migrations.AlterField(
            model_name="shsession",
            name="conversation",
            field=models.OneToOneField(
                default=django.db.models.query.QuerySet.create,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shell_session",
                related_query_name="shell_session",
                to="camille.llmconversation",
            ),
        ),
        migrations.AlterField(
            model_name="xmppchannel",
            name="conversation",
            field=models.OneToOneField(
                default=django.db.models.query.QuerySet.create,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xmpp_channel",
                related_query_name="xmpp_channel",
                to="camille.llmconversation",
            ),
        ),
        migrations.DeleteModel(
            name="MMUser",
        ),
    ]
