services:
  camille:
    image: "killruana/camille:main"
    environment:
      - "MATTERMOST_HOST=https://mattermost.jtremesay.org"
      - "MATTERMOST_ACCESS_TOKEN_FILE=camille_mattermost_access_token"
      - "CAMILLE_MODEL=bedrock:eu.anthropic.claude-sonnet-4-5-20250929-v1:0"
      - "AWS_DEFAULT_REGION=eu-central-1"
      - "AWS_ACCESS_KEY_ID_FILE=camille_aws_access_key_id"
      - "AWS_SECRET_ACCESS_KEY_FILE=camille_aws_secret_access_key"
      - "LOGFIRE_TOKEN_FILE=camille_logfire_token"
      - "TAVILY_API_KEY_FILE=tavily_api_key"
    secrets:
      - "camille_mattermost_access_token"
      - "camille_aws_access_key_id"
      - "camille_aws_secret_access_key"
      - "camille_logfire_token"
      - "tavily_api_key"

secrets:
  camille_mattermost_access_token:
    external: true
  camille_aws_access_key_id:
    external: true
  camille_aws_secret_access_key:
    external: true
  camille_logfire_token:
    external: true
  tavily_api_key:
    external: true