services:
  couchdb:
    image: couchdb
    volumes:
      - couchdb_etc:/opt/couchdb/etc/local.d/
      - couchdb_data:/opt/couchdb/data/
    networks:
      - camille
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.camille-couchdb.rule=Host(`camille.jtremesay.org`) || Host(`camille.slaanesh.org`)"
        - "traefik.http.routers.camille-couchdb.tls.certresolver=leresolver"
        - "traefik.http.services.camille-couchdb.loadbalancer.server.port=5984"

  camille:
    image: killruana/camille:main
    networks:
      - camille
    environment:
      - "MATTERMOST_HOST=https://mattermost.jtremesay.org"
      - "MATTERMOST_API_TOKEN_FILE=/run/secrets/camille_mattermost_api_token"
      - "AGENT_MODEL=gemini-2.0-flash"
      - "GEMINI_API_KEY_FILE=/run/secrets/google_api_key"
      - "TAVILY_API_KEY_FILE=/run/secrets/tavily_api_key"
      - "ENVIRONMENT=prod"
      - COUCHDB_URL_FILE=/run/secrets/camille_couchdb_url
      - WINDOW_SIZE=256
    secrets:
      - camille_mattermost_api_token
      - google_api_key
      - tavily_api_key
      - camille_couchdb_url

volumes:
  couchdb_etc:
  couchdb_data:

networks:
  camille:
  traefik_public:
    external: true

secrets:
  camille_mattermost_api_token:
    external: true
  google_api_key:
    external: true
  tavily_api_key:
    external: true
  camille_couchdb_url:
    external: true
