# Generated by Django 5.2.1 on 2025-05-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MMTeam",
            fields=[
                (
                    "id",
                    models.CharField(max_length=26, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MMUser",
            fields=[
                (
                    "id",
                    models.CharField(max_length=26, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=255)),
                ("nickname", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MMChannel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=26, primary_key=True, serialize=False),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("O", "Open"),
                            ("P", "Private"),
                            ("D", "Direct"),
                            ("G", "Group"),
                        ],
                        max_length=1,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("header", models.TextField(null=True)),
                ("purpose", models.TextField(null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        related_query_name="channel",
                        to="camille.mmteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MMMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        related_query_name="membership",
                        to="camille.mmchannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        related_query_name="membership",
                        to="camille.mmuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("channel", "user")},
            },
        ),
    ]
