# Generated by Django 6.0.1 on 2026-01-15 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_user_profile_on_user_create(apps, schema_editor):
    Profile = apps.get_model("camille", "Profile")
    User = apps.get_model(
        settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1]
    )
    for user in User.objects.all():
        Profile.objects.update_or_create(user=user)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            create_user_profile_on_user_create, reverse_code=migrations.RunPython.noop
        ),
    ]
