# Generated by Django 5.2.1 on 2025-05-09 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MMThread",
            fields=[
                (
                    "id",
                    models.CharField(max_length=26, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        related_query_name="thread",
                        to="camille.mmchannel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MMInteraction",
            fields=[
                (
                    "id",
                    models.CharField(max_length=26, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("messages_json", models.BinaryField()),
                ("tokens_count", models.PositiveIntegerField()),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        related_query_name="interaction",
                        to="camille.mmthread",
                    ),
                ),
            ],
        ),
    ]
