# Generated by Django 6.0.2 on 2026-02-03 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ApiKeyCredentials",
            fields=[
                (
                    "basecredentials_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="camille.basecredentials",
                    ),
                ),
                ("api_key", models.CharField(max_length=255)),
            ],
            bases=("camille.basecredentials",),
        ),
        migrations.CreateModel(
            name="UserCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credentials",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_credentials",
                        related_query_name="user_credential",
                        to="camille.basecredentials",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        related_query_name="credential",
                        to="camille.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AwsBedrockCredentials",
            fields=[
                (
                    "apikeycredentials_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="camille.apikeycredentials",
                    ),
                ),
                ("region_name", models.CharField(max_length=255)),
            ],
            bases=("camille.apikeycredentials",),
        ),
        migrations.CreateModel(
            name="GoogleGlaCredentials",
            fields=[
                (
                    "apikeycredentials_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="camille.apikeycredentials",
                    ),
                ),
            ],
            bases=("camille.apikeycredentials",),
        ),
        migrations.CreateModel(
            name="MistralCredentials",
            fields=[
                (
                    "apikeycredentials_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="camille.apikeycredentials",
                    ),
                ),
            ],
            bases=("camille.apikeycredentials",),
        ),
    ]
