# Generated by Django 6.0.1 on 2026-01-15 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camille', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAWSBedrockInferenceProviderCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aws_bedrock', 'AWS Bedrock'), ('google_gla', 'Google Generative AI'), ('mistral_ai', 'Mistral AI')], max_length=50)),
                ('api_key', models.TextField()),
                ('region_name', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camille.profile')),
            ],
            options={
                'abstract': False,
                'unique_together': {('profile', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='UserGoogleGLAInferenceProviderCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aws_bedrock', 'AWS Bedrock'), ('google_gla', 'Google Generative AI'), ('mistral_ai', 'Mistral AI')], max_length=50)),
                ('api_key', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camille.profile')),
            ],
            options={
                'abstract': False,
                'unique_together': {('profile', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='UserMistralAIInferenceProviderCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aws_bedrock', 'AWS Bedrock'), ('google_gla', 'Google Generative AI'), ('mistral_ai', 'Mistral AI')], max_length=50)),
                ('api_key', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camille.profile')),
            ],
            options={
                'abstract': False,
                'unique_together': {('profile', 'provider')},
            },
        ),
    ]
