# Camille - An AI assistant
# Copyright (C) Jonathan Tremesaygues <jonathan.tremesaygues@slaanesh.org>
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 6.0.4 on 2026-04-17 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_personality(apps, schema_editor):
    User = apps.get_model("auth", "User")
    AgentPersonality = apps.get_model("camille", "AgentPersonality")

    for user in User.objects.all():
        if not AgentPersonality.objects.filter(user=user, name="camille").exists():
            AgentPersonality.objects.create(
                user=user,
                name="camille",
                description="The default personality.",
                prompt_template=settings.DEFAULT_PROMPT_TEMPLATE,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("camille", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPersonality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=64)),
                ("description", models.CharField(max_length=255, blank=True)),
                ("prompt_template", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
        migrations.RunPython(
            create_default_personality, reverse_code=migrations.RunPython.noop
        ),
    ]
