# Generated by Django 6.0.4 on 2026-04-17 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_personality(apps, schema_editor):
    User = apps.get_model("auth", "User")
    AgentPersonality = apps.get_model("camille", "AgentPersonality")

    for user in User.objects.all():
        if not AgentPersonality.objects.filter(user=user, name="camille").exists():
            AgentPersonality.objects.create(
                user=user,
                name="camille",
                description="The default personality.",
                prompt_template=settings.DEFAULT_PROMPT_TEMPLATE,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("camille", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPersonality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=64)),
                ("description", models.CharField(max_length=255, blank=True)),
                ("prompt_template", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
        migrations.RunPython(
            create_default_personality, reverse_code=migrations.RunPython.noop
        ),
    ]
