# Generated by Django 6.0.2 on 2026-02-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0002_basecredentials_apikeycredentials_usercredentials_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MattermostServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_url", models.URLField()),
                ("api_token", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name="awsbedrockcredentials",
            options={
                "verbose_name": "AWS Bedrock Credentials",
                "verbose_name_plural": "AWS Bedrock Credentials",
            },
        ),
        migrations.AlterModelOptions(
            name="googleglacredentials",
            options={
                "verbose_name": "Google GLA Credentials",
                "verbose_name_plural": "Google GLA Credentials",
            },
        ),
        migrations.AlterModelOptions(
            name="mistralcredentials",
            options={
                "verbose_name": "Mistral Credentials",
                "verbose_name_plural": "Mistral Credentials",
            },
        ),
    ]
