# Generated by Django 6.0.1 on 2026-01-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0002_userawsbedrockinferenceprovidercredentials_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MattermostServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(unique=True)),
                ("token", models.CharField(max_length=255)),
            ],
        ),
    ]
