# Generated by Django 6.0.4 on 2026-04-17 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_agent_config(apps, schema_editor):
    User = apps.get_model("auth", "User")
    AgentConfig = apps.get_model("camille", "AgentConfig")
    AgentPersonality = apps.get_model("camille", "AgentPersonality")

    for user in User.objects.all():
        if not AgentConfig.objects.filter(user=user).exists():
            personality = AgentPersonality.objects.filter(
                user=user,
                name="camille",
            ).first()

            AgentConfig.objects.create(
                user=user,
                personality=personality,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("camille", "0002_agentpersonality"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="https://pydantic.dev/docs/ai/models/overview/",
                        max_length=64,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "personality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="camille.agentpersonality",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            create_default_agent_config, reverse_code=migrations.RunPython.noop
        ),
    ]
