# Generated by Django 6.0.1 on 2026-01-22 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0002_bedrockcredentials_googleglacredentials_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedrockcredentials",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="camille.profile"
            ),
        ),
        migrations.AlterField(
            model_name="googleglacredentials",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="camille.profile"
            ),
        ),
        migrations.AlterField(
            model_name="mistralaicredentials",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="camille.profile"
            ),
        ),
    ]
