# Generated by Django 6.0.1 on 2026-01-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0003_alter_bedrockcredentials_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="model_name",
            field=models.CharField(
                blank=True,
                help_text="Default model name for the profile",
                max_length=100,
                null=True,
            ),
        ),
    ]
