# Generated by Django 6.0.1 on 2026-01-15 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0003_mattermostserver"),
    ]

    operations = [
        migrations.CreateModel(
            name="MattermostTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("create_at", models.DateTimeField()),
                ("update_at", models.DateTimeField()),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camille.mattermostserver",
                    ),
                ),
            ],
            options={
                "unique_together": {("server", "team_id")},
            },
        ),
    ]
