# Generated by Django 5.2.1 on 2025-05-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0003_mmchannel_notes_mmuser_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mminteraction",
            name="messages_json",
            field=models.TextField(),
        ),
    ]
