# Generated by Django 6.0.2 on 2026-02-03 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "camille",
            "0003_mattermostserver_alter_awsbedrockcredentials_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MattermostTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        related_query_name="team",
                        to="camille.mattermostserver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MattermostChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("header", models.TextField(blank=True, null=True)),
                ("purpose", models.TextField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        related_query_name="channel",
                        to="camille.mattermostteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MattermostUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        related_query_name="user",
                        to="camille.mattermostserver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MattermostChannelMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        related_query_name="member",
                        to="camille.mattermostchannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_memberships",
                        related_query_name="channel_membership",
                        to="camille.mattermostuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("channel", "user")},
            },
        ),
    ]
