# Generated by Django 6.0.1 on 2026-01-15 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0004_mattermostteam"),
    ]

    operations = [
        migrations.CreateModel(
            name="MattermostUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("create_at", models.DateTimeField()),
                ("update_at", models.DateTimeField()),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camille.mattermostserver",
                    ),
                ),
            ],
            options={
                "unique_together": {("server", "user_id")},
            },
        ),
    ]
