# Generated by Django 6.0.1 on 2026-01-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0004_profile_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="model_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
