# Generated by Django 5.2.1 on 2025-05-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0004_alter_mminteraction_messages_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mminteraction",
            name="tokens_count",
        ),
    ]
