# Generated by Django 6.0.1 on 2026-01-22 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0005_profile_notes_alter_profile_model_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPersonality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("prompt_template", models.TextField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camille.profile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="personality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="camille.agentpersonality",
            ),
        ),
    ]
