# Generated by Django 6.0.1 on 2026-01-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0005_mattermostuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="mattermostuser",
            name="nickname",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
