# Generated by Django 6.0.4 on 2026-04-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0005_mattermostconversation_mattermostconversationrun"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GatewayCredentials",
        ),
    ]
