# Generated by Django 6.0.1 on 2026-01-15 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0006_mattermostuser_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="MattermostChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("header", models.TextField()),
                ("purpose", models.TextField()),
                ("last_post_at", models.DateTimeField()),
                ("create_at", models.DateTimeField()),
                ("update_at", models.DateTimeField()),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camille.mattermostteam",
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "channel_id")},
            },
        ),
    ]
