# Generated by Django 6.0.1 on 2026-01-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0007_llmthread_llminteraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmthread",
            name="summary",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
