# Generated by Django 6.0.5 on 2026-05-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0007_agentmemory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentconfig",
            name="notes",
        ),
    ]
