# Generated by Django 6.0.1 on 2026-01-15 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0007_mattermostchannel"),
    ]

    operations = [
        migrations.CreateModel(
            name="MattermostChannelMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        related_query_name="membership",
                        to="camille.mattermostchannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        related_query_name="membership",
                        to="camille.mattermostuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("channel", "user")},
            },
        ),
    ]
