# Generated by Django 6.0.1 on 2026-01-15 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camille', '0007_alter_mmchannel_notes_alter_mmuser_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmuser',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AWSBedrockCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aws-bedrock', 'AWS Bedrock'), ('google-gla', 'Google Generative Language API'), ('mistral-ai', 'Mistral AI')], max_length=50)),
                ('bearer_token', models.TextField()),
                ('region', models.CharField(default='eu-west-3', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camille.mmuser')),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='GoogleGLACredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aws-bedrock', 'AWS Bedrock'), ('google-gla', 'Google Generative Language API'), ('mistral-ai', 'Mistral AI')], max_length=50)),
                ('api_key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camille.mmuser')),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='MistralAICredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aws-bedrock', 'AWS Bedrock'), ('google-gla', 'Google Generative Language API'), ('mistral-ai', 'Mistral AI')], max_length=50)),
                ('api_key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camille.mmuser')),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
