# Generated by Django 6.0.1 on 2026-01-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0008_mattermostchannelmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mattermostchannel",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                related_query_name="channel",
                to="camille.mattermostteam",
            ),
        ),
        migrations.AlterField(
            model_name="mattermostteam",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                related_query_name="team",
                to="camille.mattermostserver",
            ),
        ),
        migrations.AlterField(
            model_name="mattermostuser",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                related_query_name="user",
                to="camille.mattermostserver",
            ),
        ),
        migrations.CreateModel(
            name="ProfileMattermostMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mm_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mm_mappings",
                        related_query_name="mm_mapping",
                        to="camille.mattermostuser",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mm_mappings",
                        related_query_name="mm_mapping",
                        to="camille.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "mm_user")},
            },
        ),
    ]
