# Generated by Django 6.0.1 on 2026-01-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camille', '0008_mmuser_model_awsbedrockcredentials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmuser',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
