# Generated by Django 6.0.5 on 2026-05-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0008_remove_agentconfig_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentmemory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
