# Generated by Django 6.0.5 on 2026-05-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camille", "0009_agentmemory_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconfig",
            name="debug_tools",
            field=models.BooleanField(
                default=True,
                help_text="Whether to include tool calls in the debug output.",
            ),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="debug_usage",
            field=models.BooleanField(
                default=True,
                help_text="Whether to include model usage in the debug output.",
            ),
        ),
    ]
