# Generated by Django 6.0.1 on 2026-01-25 19:18

import django.db.models.deletion
from django.db import migrations, models


def migrate_prompt_data(apps, schema_editor):
    # Create and set a "default" PersonalityPrompt for each MMUser with an old prompt
    MMUser = apps.get_model("camille", "MMUser")
    PersonalityPrompt = apps.get_model("camille", "PersonalityPrompt")
    for user in MMUser.objects.all():
        old_prompt = getattr(user, "prompt", None)
        if old_prompt:
            # No prompts should exist because the model is created in
            # this migration, so we can safely create a new one.
            prompt_instance = PersonalityPrompt.objects.create(
                user=user,
                name="default",
                description="Default prompt",
                prompt_template=old_prompt,
            )
            user.new_prompt = prompt_instance
            user.save()


def unmigrate_prompt_data(apps, schema_editor):
    # Move prompt_template from PersonalityPrompt back to MMUser.prompt
    MMUser = apps.get_model("camille", "MMUser")
    for user in MMUser.objects.all():
        prompt_instance = getattr(user, "new_prompt", None)
        if prompt_instance:
            user.prompt = prompt_instance.prompt_template
            user.save()

            # Don't need to delete the PersonalityPrompt instance, as the
            # model will be removed in this migration.


class Migration(migrations.Migration):
    dependencies = [
        ("camille", "0009_mmuser_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalityPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("prompt_template", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personality_prompts",
                        related_query_name="personality_prompt",
                        to="camille.mmuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="mmuser",
            name="new_prompt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_with_new_prompt",
                related_query_name="user_with_new_prompt",
                to="camille.personalityprompt",
            ),
        ),
        migrations.RunPython(migrate_prompt_data, unmigrate_prompt_data),
        migrations.RemoveField(
            model_name="mmuser",
            name="prompt",
        ),
        migrations.RenameField(
            model_name="mmuser",
            old_name="new_prompt",
            new_name="prompt",
        ),
    ]
