# Generated by Django 6.0.1 on 2026-01-16 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0009_alter_mattermostchannel_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mattermostchannelmember",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_memberships",
                related_query_name="channel_membership",
                to="camille.mattermostchannel",
            ),
        ),
        migrations.AlterField(
            model_name="mattermostchannelmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_memberships",
                related_query_name="channel_membership",
                to="camille.mattermostuser",
            ),
        ),
        migrations.CreateModel(
            name="MattermostTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        related_query_name="membership",
                        to="camille.mattermostteam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        related_query_name="team_membership",
                        to="camille.mattermostuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "user")},
            },
        ),
    ]
