# Generated by Django 6.0.4 on 2026-04-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camille', '0010_personalityprompt_mmuser_new_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmchannel',
            name='notes',
        ),
    ]
