# Generated by Django 6.0.1 on 2026-01-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille", "0010_alter_mattermostchannelmember_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mattermostchannel",
            name="type",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
