# Generated by Django 6.0.5 on 2026-05-24 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("camille", "0010_agentconfig_debug_tools_agentconfig_debug_usage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentconfig",
            name="debug_usage",
        ),
    ]
