# Generated by Django 5.0.6 on 2024-06-21 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="XMPPChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jid", models.CharField(max_length=255, unique=True)),
                (
                    "model",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("prompt", models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="XMPPMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("sender", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laura.xmppchannel",
                    ),
                ),
            ],
        ),
    ]
