# Generated by Django 5.0.6 on 2024-07-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DjCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.TextField()),
                ("thread_ts", models.TextField()),
                ("parent_ts", models.TextField(blank=True, default=None, null=True)),
                ("checkpoint", models.BinaryField()),
                ("metadata", models.BinaryField()),
            ],
            options={
                "unique_together": {("thread_id", "thread_ts")},
            },
        ),
        migrations.CreateModel(
            name="DjWrite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.TextField()),
                ("thread_ts", models.TextField()),
                ("task_id", models.TextField()),
                ("idx", models.IntegerField()),
                ("channel", models.TextField()),
                ("value", models.BinaryField(blank=True, default=None, null=True)),
            ],
            options={
                "unique_together": {("thread_id", "thread_ts", "task_id", "idx")},
            },
        ),
    ]
