# Generated by Django 6.0.1 on 2026-01-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camille_orgs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
